---
title: FluentAssertions
date: 2023-04-25 21:42:18
permalink: /pages/9746b1/
---

::: note 开源地址
Github：[https://github.com/nodatime/nodatime](https://github.com/fluentassertions/fluentassertions)
:::

FluentAssertions 是一个基于 .NET 的开源测试工具库，它提供了一种流畅的、可读性强的测试风格，使得测试代码更加易于编写和维护。本文将介绍 FluentAssertions 的使用方法和示例，以帮助 .NET 开发人员更好地掌握这个工具库。
## 安装

FluentAssertions 可以通过 NuGet 包管理器来安装，只需要在 Visual Studio 中打开 NuGet 包管理器，搜索 "FluentAssertions" 并安装即可。也可以在控制台中使用以下命令来安装：

```mathematica

Install-Package FluentAssertions
```


## 使用示例
### 基本使用

下面是一个简单的使用示例，展示了如何使用 FluentAssertions 来断言一个变量是否等于期望值：

```csharp

var actualValue = 10;
actualValue.Should().Be(10);
```



在这个例子中，我们创建了一个整数变量 `actualValue`，然后使用 `Should()` 方法来开始一个断言，并使用 `Be()` 方法来断言变量是否等于 10。如果 `actualValue` 不等于 10，该断言将抛出异常，测试失败。
### 集合断言

FluentAssertions 还提供了一些方法来测试集合的内容。下面是一个示例，展示了如何使用 `Contain()` 方法来测试一个字符串列表是否包含某个特定的字符串：

```csharp

var fruits = new List<string> { "apple", "banana", "orange" };
fruits.Should().Contain("apple");
```



在这个例子中，我们创建了一个字符串列表 `fruits`，然后使用 `Contain()` 方法来断言列表是否包含字符串 "apple"。如果列表不包含该字符串，该断言将抛出异常，测试失败。
### 异常断言

有时候我们希望测试代码是否能够正确地抛出异常。FluentAssertions 提供了一些方法来测试代码是否抛出了预期的异常。下面是一个示例，展示了如何使用 `Throw()` 方法来测试一个方法是否抛出了预期的异常：

```csharp

Action action = () => { throw new Exception("error"); };
action.Should().Throw<Exception>().WithMessage("error");
```



在这个例子中，我们创建了一个匿名方法 `action`，该方法会抛出一个异常。然后我们使用 `Throw()` 方法来断言该方法是否抛出了 `Exception` 异常，并使用 `WithMessage()` 方法来断言异常消息是否为 "error"。如果方法未抛出预期的异常，该断言将抛出异常，测试失败。
### 嵌套断言

有时候我们希望测试一个对象的属性是否满足特定条件。FluentAssertions 允许我们使用嵌套断言来测试对象的属性。下面是一个示例，展示了如何使用嵌套断言来测试一个自定义类型的属性：

```csharp

public class Person
{
    public string Name { get; set; }
    public int Age { get; set; }
}

var person = new Person { Name = "Alice", Age = 30 };
person.Should().Match<Person>(p => p.Name == "Alice" && p.Age == 30);

```swift

在这个例子中，我们创建了一个自定义类型 `Person`，该类型包含两个属性 `Name` 和 `Age`。然后我们创建了一个 `Person` 对象 `person`，并使用 `Match()` 方法来断言 `person` 对象是否满足特定的条件。在这个例子中，我们使用 Lambda 表达式来定义条件，断言 `person` 对象的 `Name` 属性等于 "Alice"，`Age` 属性等于 30。如果 `person` 对象的属性不满足条件，该断言将抛出异常，测试失败。

### 自定义断言

有时候我们需要测试一些比较复杂的条件，这时候可以通过编写自定义断言来实现。下面是一个示例，展示了如何编写一个自定义断言来测试一个整数是否为奇数：

```csharp
public class OddNumberAssertion : Assertion<OddNumberAssertion, int>
{
    public AndConstraint<OddNumberAssertion> BeOdd()
    {
        Execute.Assertion
            .ForCondition(Subject % 2 == 1)
            .FailWith("Expected {context:subject} to be odd, but found {0}.", Subject);

        return new AndConstraint<OddNumberAssertion>(this);
    }
}

public static class OddNumberAssertionExtensions
{
    public static OddNumberAssertion Should(this int actualValue)
    {
        return new OddNumberAssertion { Subject = actualValue };
    }
}

var actualValue = 5;
actualValue.Should().BeOdd();
```



在这个例子中，我们定义了一个自定义断言类 `OddNumberAssertion`，该类继承自 `Assertion<OddNumberAssertion, int>`，并提供了一个 `BeOdd()` 方法来测试一个整数是否为奇数。在 `BeOdd()` 方法中，我们使用 FluentAssertions 提供的 `ForCondition()` 方法来定义断言条件，如果条件不满足，该方法将抛出异常。然后我们定义了一个扩展方法 `Should()`，该方法接收一个整数参数，返回一个 `OddNumberAssertion` 实例。最后，我们创建了一个整数变量 `actualValue`，并使用 `Should()` 方法来断言该变量是否为奇数。如果 `actualValue` 不是奇数，该断言将抛出异常，测试失败。
## 结论

在本文中，我们介绍了 FluentAssertions 的安装和使用方法，并提供了一些使用示例，包括基本断言、集合断言、异常断言、嵌套断言和自定义断言。FluentAssertions 提供了一种流畅的、可读性强的测试风格，使得测试代码更加易于编写和维护。如果你还没有使用 FluentAssertions，现在是时候尝试一下了！
